[2024-05-06T03:11:25.301+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T03:10:24.544407+00:00 [queued]>
[2024-05-06T03:11:25.317+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T03:10:24.544407+00:00 [queued]>
[2024-05-06T03:11:25.318+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-06T03:11:25.337+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models_task> on 2024-05-06 03:10:24.544407+00:00
[2024-05-06T03:11:25.352+0000] {standard_task_runner.py:57} INFO - Started process 124 to run task
[2024-05-06T03:11:25.361+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'train_models_task', 'manual__2024-05-06T03:10:24.544407+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpxbep3dl6']
[2024-05-06T03:11:25.367+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask train_models_task
[2024-05-06T03:11:25.469+0000] {task_command.py:415} INFO - Running <TaskInstance: main.train_models_task manual__2024-05-06T03:10:24.544407+00:00 [running]> on host 172d1424854d
[2024-05-06T03:11:25.608+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='train_models_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T03:10:24.544407+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T03:10:24.544407+00:00'
[2024-05-06T03:11:27.107+0000] {warnings.py:109} WARNING - /opt/***/dags/main.py:113: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2024-05-06T03:11:29.116+0000] {logging_mixin.py:151} WARNING - 2024/05/06 03:11:29 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T03:11:31.361+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T03:14:20.238+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 182, in train_models
    mlflow.log_params("best_params", search.best_params_)
TypeError: log_params() takes 1 positional argument but 2 were given
[2024-05-06T03:14:20.257+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=main, task_id=train_models_task, execution_date=20240506T031024, start_date=20240506T031125, end_date=20240506T031420
[2024-05-06T03:14:20.289+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 205 for task train_models_task (log_params() takes 1 positional argument but 2 were given; 124)
[2024-05-06T03:14:20.352+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-06T03:14:20.387+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
