[2024-05-06T03:44:22.640+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T03:39:17.453967+00:00 [queued]>
[2024-05-06T03:44:22.659+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T03:39:17.453967+00:00 [queued]>
[2024-05-06T03:44:22.660+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-05-06T03:44:22.683+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models_task> on 2024-05-06 03:39:17.453967+00:00
[2024-05-06T03:44:22.699+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2024-05-06T03:44:22.708+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'train_models_task', 'manual__2024-05-06T03:39:17.453967+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp_601zmb6']
[2024-05-06T03:44:22.715+0000] {standard_task_runner.py:85} INFO - Job 212: Subtask train_models_task
[2024-05-06T03:44:22.828+0000] {task_command.py:415} INFO - Running <TaskInstance: main.train_models_task manual__2024-05-06T03:39:17.453967+00:00 [running]> on host 6a3971e82789
[2024-05-06T03:44:22.964+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='train_models_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T03:39:17.453967+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T03:39:17.453967+00:00'
[2024-05-06T03:44:23.175+0000] {warnings.py:109} WARNING - /opt/***/dags/main.py:113: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2024-05-06T03:44:24.962+0000] {logging_mixin.py:151} WARNING - 2024/05/06 03:44:24 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T03:44:25.385+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T03:46:54.413+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 182, in train_models
    mlflow.log_params(search.best_params_)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 702, in log_params
    MlflowClient().log_batch(run_id=run_id, metrics=[], params=params_arr, tags=[])
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 991, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 389, in log_batch
    self.store.log_batch(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 321, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 214, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Changing param values is not allowed. Params were already logged='[{'key': 'classifier__max_depth', 'old_value': '[1, 2, 3, 10]', 'new_value': '10'}, {'key': 'classifier__n_estimators', 'old_value': '[10, 11]', 'new_value': '11'}]' for run ID='325a0f23dadf4673b5aa50e0425f5334'.
[2024-05-06T03:46:54.446+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=main, task_id=train_models_task, execution_date=20240506T033917, start_date=20240506T034422, end_date=20240506T034654
[2024-05-06T03:46:54.496+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 212 for task train_models_task (INVALID_PARAMETER_VALUE: Changing param values is not allowed. Params were already logged='[{'key': 'classifier__max_depth', 'old_value': '[1, 2, 3, 10]', 'new_value': '10'}, {'key': 'classifier__n_estimators', 'old_value': '[10, 11]', 'new_value': '11'}]' for run ID='325a0f23dadf4673b5aa50e0425f5334'.; 199)
[2024-05-06T03:46:54.557+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-06T03:46:54.593+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
