[2024-05-06T15:42:33.691+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T15:41:18.455209+00:00 [queued]>
[2024-05-06T15:42:33.749+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T15:41:18.455209+00:00 [queued]>
[2024-05-06T15:42:33.750+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-06T15:42:33.810+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models_task> on 2024-05-06 15:41:18.455209+00:00
[2024-05-06T15:42:33.870+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2024-05-06T15:42:33.899+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'train_models_task', 'manual__2024-05-06T15:41:18.455209+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpsvq7ab3s']
[2024-05-06T15:42:33.912+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask train_models_task
[2024-05-06T15:42:34.047+0000] {task_command.py:415} INFO - Running <TaskInstance: main.train_models_task manual__2024-05-06T15:41:18.455209+00:00 [running]> on host 9ff1c0aeaac5
[2024-05-06T15:42:34.255+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='train_models_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T15:41:18.455209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T15:41:18.455209+00:00'
[2024-05-06T15:42:36.289+0000] {warnings.py:109} WARNING - /opt/***/dags/main.py:114: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2024-05-06T15:42:38.867+0000] {logging_mixin.py:151} WARNING - 2024/05/06 15:42:38 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T15:42:41.247+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T15:45:50.897+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

[2024-05-06T15:45:51.565+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2024-05-06T15:45:52.119+0000] {logging_mixin.py:151} WARNING - Registered model 'best_RandomForestClassifier' already exists. Creating a new version of this model...
[2024-05-06T15:45:52.294+0000] {logging_mixin.py:151} WARNING - 2024/05/06 15:45:52 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: best_RandomForestClassifier, version 14
[2024-05-06T15:45:52.295+0000] {logging_mixin.py:151} WARNING - Created version '14' of model 'best_RandomForestClassifier'.
[2024-05-06T15:45:52.298+0000] {logging_mixin.py:151} INFO - Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide_metformin', 'glipizide_metformin',
       'metformin_rosiglitazone', 'metformin_pioglitazone', 'change',
       'diabetesMed', 'diag_1', 'diag_2', 'diag_3', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses'],
      dtype='object')
[2024-05-06T15:45:52.392+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T15:49:14.187+0000] {logging_mixin.py:151} WARNING - Registered model 'best_DecisionTreeClassifier' already exists. Creating a new version of this model...
[2024-05-06T15:49:14.265+0000] {logging_mixin.py:151} WARNING - 2024/05/06 15:49:14 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: best_DecisionTreeClassifier, version 6
[2024-05-06T15:49:14.265+0000] {logging_mixin.py:151} WARNING - Created version '6' of model 'best_DecisionTreeClassifier'.
[2024-05-06T15:49:14.267+0000] {logging_mixin.py:151} INFO - Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide_metformin', 'glipizide_metformin',
       'metformin_rosiglitazone', 'metformin_pioglitazone', 'change',
       'diabetesMed', 'diag_1', 'diag_2', 'diag_3', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses'],
      dtype='object')
[2024-05-06T15:49:14.547+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-05-06T15:49:14.572+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main, task_id=train_models_task, execution_date=20240506T154118, start_date=20240506T154233, end_date=20240506T154914
[2024-05-06T15:49:14.671+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-05-06T15:49:14.705+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
