[2024-05-06T05:01:17.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T05:00:12.755607+00:00 [queued]>
[2024-05-06T05:01:17.188+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.train_models_task manual__2024-05-06T05:00:12.755607+00:00 [queued]>
[2024-05-06T05:01:17.189+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-06T05:01:17.215+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models_task> on 2024-05-06 05:00:12.755607+00:00
[2024-05-06T05:01:17.236+0000] {standard_task_runner.py:57} INFO - Started process 140 to run task
[2024-05-06T05:01:17.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'train_models_task', 'manual__2024-05-06T05:00:12.755607+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpnpamzqwp']
[2024-05-06T05:01:17.250+0000] {standard_task_runner.py:85} INFO - Job 236: Subtask train_models_task
[2024-05-06T05:01:17.357+0000] {task_command.py:415} INFO - Running <TaskInstance: main.train_models_task manual__2024-05-06T05:00:12.755607+00:00 [running]> on host 60830aa03b4d
[2024-05-06T05:01:17.561+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='train_models_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T05:00:12.755607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T05:00:12.755607+00:00'
[2024-05-06T05:01:17.809+0000] {warnings.py:109} WARNING - /opt/***/dags/main.py:113: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2024-05-06T05:01:19.966+0000] {logging_mixin.py:151} WARNING - 2024/05/06 05:01:19 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T05:01:21.569+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T05:04:30.991+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

[2024-05-06T05:04:31.722+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2024-05-06T05:04:32.332+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-05-06T05:08:03.815+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-05-06T05:08:03.845+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main, task_id=train_models_task, execution_date=20240506T050012, start_date=20240506T050117, end_date=20240506T050803
[2024-05-06T05:08:03.951+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-05-06T05:08:03.990+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
